spring.application.name: carros-electricos
spring.datasource.url: jdbc:sqlserver://sqlnoprod.database.windows.net:1433;database=Db_App_ECM_NoProd;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username: usrappecmnp@sqlnoprod
spring.datasource.password: JJpJ8=VL]~{t
spring.datasource.driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.maximum-pool-size: 10
spring.datasource.hikari.minimum-idle: 5
spring.datasource.hikari.idle-timeout: 30000
spring.datasource.hikari.connection-timeout: 20000
spring.datasource.hikari.auto-commit: true
spring.jpa.show-sql: true