spring.application.name: carros-electricos
spring.application.version: 2
spring.datasource:
  url: jdbc:sqlserver://sqlnoprod.database.windows.net:1433;database=Db_App_ECM_NoProd;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  username: usrappecmnp@sqlnoprod
  password: JJpJ8=VL]~{t
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  hikari.maximum-pool-size: 10
  hikari.minimum-idle: 5
  hikari.idle-timeout: 30000
  hikari.connection-timeout: 20000
  hikari.auto-commit: true

spring.jpa.show-sql: true
logging:
  level.root: INFO


gpc.external.authentication.url: https://gpc-external-authentication-dev.puertocartagena.com:8081